### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError caused by dependency conflict issue due to multiple versions of org.hamcrest:hamcrest-core:jar

### ISSUE THREAD

**Issue by LeoAugust19** [vipshop/Saturn#477]
Hi, in **com.vip.saturn:saturn-core:jar:master-SNAPSHOT**, as show in the following dependency tree, there are multiple versions of **org.hamcrest:hamcrest-core:jar**.
Based on Maven's "nearest wins strategy", only the older version **org.hamcrest:hamcrest-core:jar:1.1** that nearer to the root (host project) will be loaded.

However, the method **<org.hamcrest.MatcherAssert: void assertThat(java.lang.String,java.lang.Object,org.hamcrest.Matcher)>** only defined in the shadowed version org.hamcrest:hamcrest-core:jar:1.3 and not included in version 1.1. when referencing this method, we crashes with the java.lang.NoSuchMethodError exception.

### Dependency tree:
com.vip.saturn:saturn-core:jar:master-SNAPSHOT
+- org.mockito:mockito-core:jar:1.10.19:test
|  +- **org.hamcrest:hamcrest-core:jar:1.1:test**
|  \- org.objenesis:objenesis:jar:2.1:test
+- junit:junit:jar:4.12:test
|  \- **(org.hamcrest:hamcrest-core:jar:1.3:test - omitted for conflict with 1.1)**
\- org.powermock:powermock-module-junit4:jar:1.6.3:test
   +- (junit:junit:jar:4.12:test - version managed from 4.11; omitted for duplicate)
   \- org.powermock:powermock-module-junit4-common:jar:1.6.3:test
      +- (junit:junit:jar:4.12:test - version managed from 4.4; omitted for duplicate)
      +- (org.powermock:powermock-core:jar:1.6.3:test - omitted for duplicate)
      \- (org.powermock:powermock-reflect:jar:1.6.3:test - omitted for duplicate)

### Solution
Use hamcrest-core 1.3 via dependencyManagement.

### Further question
Do you need stack trace or test case for further investigation? I can try to provide you more information. ;-)

Hope this report can help you!

Best regards,
Leo

**Comment by LeoAugust19** [comment]
@hebelala Hi, Using the test case you get the following stack trace:
### Stack trace
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/MatcherAssert
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)

### Test case
[Test1.txt](https://github.com/vipshop/Saturn/files/2282276/Test1.txt)

May I pull a request to fix this issue?

**Comment by LeoAugust19** [comment]
@hebelala Thanks a lot for your feedback. I will submit a PR later. ：-p
