### ISSUE TITLE
Executor执行spring-boot工程的类时提示java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by universefeeler** [vipshop/Saturn#484]
java.lang.ClassNotFoundException: com.show.interlive.business.handler.DistributeTaskExecutor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.vip.saturn.job.executor.JobClassLoader.loadClass(JobClassLoader.java:21)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.vip.saturn.job.java.SaturnJavaJob.reflectionInvokeInitMethodsOfJobBusinessInstance(SaturnJavaJob.java:88)
        at com.vip.saturn.job.java.SaturnJavaJob.createJobBusinessInstanceIfNecessary(SaturnJavaJob.java:70)
        at com.vip.saturn.job.java.SaturnJavaJob.init(SaturnJavaJob.java:36)
        at com.vip.saturn.job.basic.JobScheduler.createJob(JobScheduler.java:204)
        at com.vip.saturn.job.basic.JobScheduler.init(JobScheduler.java:150)
        at com.vip.saturn.job.executor.InitNewJobService$InitNewJobListener.initJobScheduler(InitNewJobService.java:154)
        at com.vip.saturn.job.executor.InitNewJobService$InitNewJobListener.childEvent(InitNewJobService.java:124)
        at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732)
        at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kfchu** [comment]
@universefeeler com.show.interlive.business.handler.DistributeTaskExecutor 应该是你的作业classloader其中一个类吧？我认为这个跟你的打包有关系，你检查一下？

**Comment by universefeeler** [comment]
@kfchu 好 我检查下

**Comment by universefeeler** [comment]
> 出现同样的问题 executor已经启动成功了 能帮忙看下？可以远程帮忙吗？ 加个微信znq1577237702
do it as spring boot examples in Saturn
