### ISSUE TITLE
启动saturn-executor的时候报错VIP_SATURN_PRG is not configured，但是好像没有找到要如何配置

### ISSUE THREAD

**Issue by dyc87112** [vipshop/Saturn#488]
com.vip.saturn.job.exception.SaturnJobException: VIP_SATURN_PRG is not configured
	at com.vip.saturn.job.executor.RestartAndDumpService.validateConfigured(RestartAndDumpService.java:66)
	at com.vip.saturn.job.executor.RestartAndDumpService.validateFile(RestartAndDumpService.java:54)
	at com.vip.saturn.job.executor.RestartAndDumpService.start(RestartAndDumpService.java:45)
	at com.vip.saturn.job.executor.SaturnExecutorService.registerExecutor0(SaturnExecutorService.java:131)
	at com.vip.saturn.job.executor.SaturnExecutorService.registerExecutor(SaturnExecutorService.java:50)
	at com.vip.saturn.job.executor.SaturnExecutor.registerExecutor(SaturnExecutor.java:397)
	at com.vip.saturn.job.executor.SaturnExecutor.execute(SaturnExecutor.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vip.saturn.job.executor.Main.startExecutor(Main.java:138)
	at com.vip.saturn.job.executor.Main.main(Main.java:178)

**Comment by dyc87112** [comment]
具体错误如下：

```bash
$ ./saturn-executor.sh start -n www.abc.com -e executor_001 -sld logs
readlink: illegal option -- f
usage: readlink [-n] [file ...]
[2018-09-12 10:33:39] [saturn-executor] The jmx port is 24501.
[2018-09-12 10:33:39] [saturn-executor] Begin to start executor.
[2018-09-12 10:33:39] [saturn-executor] The java version is 1.8.0_151
[2018-09-12 10:33:39] [saturn-executor] Log redirects to logs
[2018-09-12 10:33:39] [saturn-executor] Starting...
./saturn-executor.sh: line 266: kill: (67330) - No such process
[2018-09-12 10:33:42] [saturn-executor] Saturn executor start is failed ! See logs/saturn-nohup.out for more information.

$ tail -n 200 logs/saturn-nohup.out
-XX:+AlwaysPreTouch -XX:AutoBoxCacheMax=20000 -XX:CMSInitiatingOccupancyFraction=75 -XX:ErrorFile=logs/hs_err_%p.log -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=logs/ -XX:InitialHeapSize=2147483648 -XX:InitialTenuringThreshold=6 -XX:+ManagementServer -XX:MaxHeapSize=2147483648 -XX:MaxMetaspaceSize=536870912 -XX:MaxTenuringThreshold=6 -XX:MetaspaceSize=268435456 -XX:NewRatio=1 -XX:OldPLABSize=16 -XX:-OmitStackTraceInFastThrow -XX:+ParallelRefProcEnabled -XX:+PrintCommandLineFlags -XX:+PrintGC -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:-UseBiasedLocking -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC
Done initial localhostip: 10.211.55.2
start check result: [ERROR]
com.vip.saturn.job.exception.SaturnJobException: VIP_SATURN_PRG is not configured
	at com.vip.saturn.job.executor.RestartAndDumpService.validateConfigured(RestartAndDumpService.java:66)
	at com.vip.saturn.job.executor.RestartAndDumpService.validateFile(RestartAndDumpService.java:54)
	at com.vip.saturn.job.executor.RestartAndDumpService.start(RestartAndDumpService.java:45)
	at com.vip.saturn.job.executor.SaturnExecutorService.registerExecutor0(SaturnExecutorService.java:131)
	at com.vip.saturn.job.executor.SaturnExecutorService.registerExecutor(SaturnExecutorService.java:50)
	at com.vip.saturn.job.executor.SaturnExecutor.registerExecutor(SaturnExecutor.java:397)
	at com.vip.saturn.job.executor.SaturnExecutor.execute(SaturnExecutor.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vip.saturn.job.executor.Main.startExecutor(Main.java:138)
	at com.vip.saturn.job.executor.Main.main(Main.java:178)
```

**Comment by kfchu** [comment]
@dyc87112 是因为你用mac的原因对吧？

**Comment by dyc87112** [comment]
@kfchu 是的
