### ISSUE TITLE
saturn-executor 启动报错

### ISSUE THREAD

**Issue by jackznq** [vipshop/Saturn#510]
one initial localhostip: 172.16.140.1
java.lang.Exception: Please configure the parameter VIP_SATURN_CONSOLE_URI with env or -D
	at com.vip.saturn.job.executor.SaturnExecutor.discover(SaturnExecutor.java:222)
	at com.vip.saturn.job.executor.SaturnExecutor.execute(SaturnExecutor.java:323)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vip.saturn.job.executor.Main.startExecutor(Main.java:138)
	at com.vip.saturn.job.executor.Main.main(Main.java:178)

启动命令是  sudo ./saturn-executor.sh start -n www.abc.com -e exe01 -env dev   mac 环境下的

**Comment by iKenApple** [comment]
@jackznq  你需要把console的ip:port设置到VIP_SATURN_CONSOLE_URI环境变量中

**Comment by kfchu** [comment]
@iKenApple 正解。
