### ISSUE TITLE
java.util.regex.PatternSyntaxException: Unclosed group near index 282

### ISSUE THREAD

**Issue by xiaoxing598** [vipshop/Saturn#556]
简单的设置如下则报错。版本号: 3.2.0

`分片参数：0=echo 'xxx'`

```
[2018-12-13 21:01:14.526] [ERROR] [Saturn-CountryJavaJob-1-thread-1] [com.vip.saturn.job.shell.ScriptJobRunner] >>> [{CountryJavaJob}] msg={CountryJavaJob}-{0} Exception
java.util.regex.PatternSyntaxException: Unclosed group near index 282
\$\{?(PATH|HISTCONTROL|GREP_OPTIONS|HISTSIZE|TERM|LANG|XDG_SESSION_ID|PS1|VIP_SATURN_CONSOLE_CLUSTER|MAIL|LOGNAME|PWD|_|$(RETVAL|SHELL|LESSOPEN|VIP_SATURN_CONSOLE_URI|SSH_CLIENT|SSH_TTY|USER|CONSOLE_ZK_CLUSTER_MAPPING|SSH_CONNECTION|HOSTNAME|LS_COLORS|XDG_RUNTIME_DIR|HOME|SHLVL)\}?
        at java.util.regex.Pattern.error(Pattern.java:1957)
        at java.util.regex.Pattern.accept(Pattern.java:1815)
        at java.util.regex.Pattern.group0(Pattern.java:2910)
        at java.util.regex.Pattern.sequence(Pattern.java:2053)
        at java.util.regex.Pattern.expr(Pattern.java:1998)
        at java.util.regex.Pattern.compile(Pattern.java:1698)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at com.vip.saturn.job.utils.ScriptPidUtils.filterEnvInCmdStr(ScriptPidUtils.java:572)
        at com.vip.saturn.job.shell.ScriptJobRunner.createCommandLine(ScriptJobRunner.java:88)
        at com.vip.saturn.job.shell.ScriptJobRunner.execute(ScriptJobRunner.java:164)
        at com.vip.saturn.job.shell.ScriptJobRunner.runJob(ScriptJobRunner.java:137)
        at com.vip.saturn.job.shell.SaturnScriptJob.innerHandle(SaturnScriptJob.java:142)
        at com.vip.saturn.job.shell.SaturnScriptJob.innerHandleWithListener(SaturnScriptJob.java:115)
        at com.vip.saturn.job.shell.SaturnScriptJob$1.run(SaturnScriptJob.java:67)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by xiaoxing598** [comment]
问题已经解决。
