### ISSUE TITLE
为何一直连不上console呢

### ISSUE THREAD

**Issue by jay763190097** [vipshop/Saturn#577]
![_ _20190120113349](https://user-images.githubusercontent.com/16317178/51434933-68825980-1ca7-11e9-9a26-5ce8517f3ed7.png)

```shell
mvn saturn:run -Dnamespace=www.abc.com -DexecutorName=exec01 -DVIP_SATURN_CONSOLE_URI=http://192.168.0.6:9088

```

```
[2019-01-20 11:12:43.443] [INFO] [Thread-1] [com.vip.saturn.job.executor.SaturnExecutor] >>> [EXECUTOR_SHUTDOWN] msg=Try to stop executor exec01
[2019-01-20 11:12:43.451] [INFO] [Thread-1] [com.vip.saturn.job.executor.SaturnExecutor] >>> [EXECUTOR_SHUTDOWN] msg=The executor exec01 is stopped
[2019-01-20 11:12:43.452] [INFO] [Thread-1] [com.vip.saturn.job.executor.SaturnExecutor] >>> [EXECUTOR_INIT] msg=start to discover from saturn console
[2019-01-20 11:12:43.709] [ERROR] [Thread-1] [com.vip.saturn.job.executor.SaturnExecutor] >>> [EXECUTOR_INIT] msg=Fail to discover from saturn console. 
com.vip.saturn.job.exception.SaturnExecutorException: Fail to discover from saturn console. 
        at com.vip.saturn.job.executor.SaturnExecutor.handleDiscoverException(SaturnExecutor.java:372)
        at com.vip.saturn.job.executor.SaturnExecutor.discover(SaturnExecutor.java:336)
        at com.vip.saturn.job.executor.SaturnExecutor.execute(SaturnExecutor.java:409)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vip.saturn.job.executor.Main.startExecutor(Main.java:165)
        at com.vip.saturn.job.executor.Main.main(Main.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vip.saturn.job.plugin.maven.SaturnJobRunMojo$1.run(SaturnJobRunMojo.java:128)
        at java.lang.Thread.run(Thread.java:748)
[2019-01-20 11:12:43.711] [ERROR] [Thread-1] [c.v.s.job.executor.SaturnExecutorExtensionDefault] >>> [EXECUTOR_INIT] msg=fail to start executor
com.vip.saturn.job.exception.SaturnExecutorException: Fail to discover from saturn console. 
        at com.vip.saturn.job.executor.SaturnExecutor.handleDiscoverException(SaturnExecutor.java:372)
        at com.vip.saturn.job.executor.SaturnExecutor.discover(SaturnExecutor.java:336)
        at com.vip.saturn.job.executor.SaturnExecutor.execute(SaturnExecutor.java:409)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vip.saturn.job.executor.Main.startExecutor(Main.java:165)
        at com.vip.saturn.job.executor.Main.main(Main.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vip.saturn.job.plugin.maven.SaturnJobRunMojo$1.run(SaturnJobRunMojo.java:128)
        at java.lang.Thread.run(Thread.java:748)
[2019-01-20 11:12:43.711] [INFO] [Thread-1] [com.vip.saturn.job.executor.SaturnExecutor] >>> [EXECUTOR_SHUTDOWN] msg=Try to stop executor exec01
[2019-01-20 11:12:43.711] [INFO] [Thread-1] [com.vip.saturn.job.executor.SaturnExecutor] >>> [EXECUTOR_SHUTDOWN] msg=The executor exec01 is stopped
com.vip.saturn.job.exception.SaturnExecutorException: Fail to discover from saturn console. 
        at com.vip.saturn.job.executor.SaturnExecutor.handleDiscoverException(SaturnExecutor.java:372)
        at com.vip.saturn.job.executor.SaturnExecutor.discover(SaturnExecutor.java:336)
        at com.vip.saturn.job.executor.SaturnExecutor.execute(SaturnExecutor.java:409)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vip.saturn.job.executor.Main.startExecutor(Main.java:165)
        at com.vip.saturn.job.executor.Main.main(Main.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vip.saturn.job.plugin.maven.SaturnJobRunMojo$1.run(SaturnJobRunMojo.java:128)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by jay763190097** [comment]
这个我是先配置的namespace哦，截图第一张浏览器地址栏可以看出，www.abc.com是配置的域名

**Comment by GuoHuiChen** [comment]
![image](https://user-images.githubusercontent.com/987453/51447459-5bbe3e00-1d59-11e9-9b8f-176179be3edc.png)
注意，系统配置里面这个设置， 是否和
![image](https://user-images.githubusercontent.com/987453/51447470-75f81c00-1d59-11e9-89d6-a49c1764d1c1.png)这里一致。 或者空着，不设置试试。

**Comment by jay763190097** [comment]
用的官方的例子，docker部署的
![_ _20190122224948](https://user-images.githubusercontent.com/16317178/51543357-56b3d880-1e98-11e9-94da-6de63a3087c0.png)

![_ _20190122225034](https://user-images.githubusercontent.com/16317178/51543390-67644e80-1e98-11e9-8b98-28fb81860992.png)
![_ _20190122225101](https://user-images.githubusercontent.com/16317178/51543418-7945f180-1e98-11e9-9f38-0a933fded9eb.png)
![_ _20190122225145](https://user-images.githubusercontent.com/16317178/51543431-84008680-1e98-11e9-92cf-ecbd21c5f656.png)
![_ _20190122225341](https://user-images.githubusercontent.com/16317178/51543469-967ac000-1e98-11e9-9acf-e75aa731acad.png)
难道是乱码影响了？

**Comment by qiaojiang2** [comment]
老哥们最终解决了吗？

**Comment by qiaojiang2** [comment]
> 用的官方的例子，docker部署的
> ![_ _20190122224948](https://user-images.githubusercontent.com/16317178/51543357-56b3d880-1e98-11e9-94da-6de63a3087c0.png)
> 
> ![_ _20190122225034](https://user-images.githubusercontent.com/16317178/51543390-67644e80-1e98-11e9-8b98-28fb81860992.png)
> ![_ _20190122225101](https://user-images.githubusercontent.com/16317178/51543418-7945f180-1e98-11e9-9f38-0a933fded9eb.png)
> ![_ _20190122225145](https://user-images.githubusercontent.com/16317178/51543431-84008680-1e98-11e9-92cf-ecbd21c5f656.png)
> ![_ _20190122225341](https://user-images.githubusercontent.com/16317178/51543469-967ac000-1e98-11e9-9acf-e75aa731acad.png)
> 难道是乱码影响了？
> ![_ _20190122225609](https://user-images.githubusercontent.com/16317178/51543622-f5d8d000-1e98-11e9-9116-6bca59bf732b.png)

解决了吗，最后？

**Comment by jay763190097** [comment]
@qiaojiang2 我没有，你解决了么？

**Comment by tomsean** [comment]
同样遇到相同的问题
